package com.ani.octopus.service.agent.service.aniservice;

import com.ani.service.bus.core.application.dto.AniServiceDto;
import com.ani.service.bus.core.application.dto.AniServiceRegisterDto;

/**
 * The interface of third party service to register their client on Anicloud Platform.
 *
 * <br>
 * Created by zhaoyu on 15-10-31.
 */
public interface AniServiceManager {

    /**
     * register your service on anicloud platform
     * if aniServiceId is null, create a new AniService on Anicloud Platform
     * if aniServiceId is not null, update the information of AniService.
     * @param registerDto your service basic information.
     * @return include more information which generated by Anicloud Platform.
     * @throws Exception operation failed exception
     */
    AniServiceDto register(AniServiceRegisterDto registerDto) throws Exception;

    /**
     * get AniServiceDto by AniServiceId and clientSecret
     * @param aniServiceId third party Application unique ID
     * @param clientSecret client secret
     * @return AniServiceDto
     * @throws Exception operation failed exception
     */
    AniServiceDto getByAniService(String aniServiceId, String clientSecret) throws Exception;
}
