package com.ani.octopus.service.agent.service.aniservice;

import com.ani.service.bus.core.application.dto.AniServiceDto;
import com.ani.service.bus.core.application.dto.AniServiceRegisterDto;

/**
 * Created by zhaoyu on 15-10-31.
 */
public interface AniServiceManager {
    /**
     * register your service on anicloud platform
     * if aniServiceId is null, create a new AniService on Anicloud platform
     * if aniServiceId is not null, update the information of AniService.
     * @param registerDto your service basic information.
     * @return include more information which generated by anicloud platform.
     */
    AniServiceDto register(AniServiceRegisterDto registerDto) throws Exception;

    /**
     * get AniServiceDto by AniServiceId and clientSecret
     * @param aniServiceId
     * @param clientSecret
     * @return
     * @throws Exception
     */
    AniServiceDto getByAniService(String aniServiceId, String clientSecret) throws Exception;
}
